### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Config\Loader\FileLoader'

### ISSUE THREAD

**Issue by GautierArc** [webnet-fr/database-anonymizer#12]
Hi,
I installed the database-anonymizer globally with the command `composer global require webnet-fr/database-anonymizer`. 
When I run `database-anonymizer --help` or simply `database-anonymizer` I get this error:

```
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Config\Loader\FileLoader' not found in /Users/toto/.composer/vendor/symfony/dependency-injection/Loader/FileLoader.php:32
Stack trace:
#0 /Users/toto/.composer/vendor/composer/ClassLoader.php(571): include()
#1 /Users/toto/.composer/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/toto...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#3 /Users/toto/.composer/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(37): spl_autoload_call('Symfony\\Compone...')
#4 /Users/toto/.composer/vendor/composer/ClassLoader.php(571): include('/Users/toto...')
#5 /Users/toto/.composer/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/toto...')
#6 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#7 /Users/toto/.composer/vendor/webnet-fr/database-anonymize in /Users/toto/.composer/vendor/symfony/dependency-injection/Loader/FileLoader.php on line 32

Fatal error: Uncaught Error: Class 'Symfony\Component\Config\Loader\FileLoader' not found in /Users/toto/.composer/vendor/symfony/dependency-injection/Loader/FileLoader.php:32
Stack trace:
#0 /Users/toto/.composer/vendor/composer/ClassLoader.php(571): include()
#1 /Users/toto/.composer/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/toto...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#3 /Users/toto/.composer/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(37): spl_autoload_call('Symfony\\Compone...')
#4 /Users/toto/.composer/vendor/composer/ClassLoader.php(571): include('/Users/toto...')
#5 /Users/toto/.composer/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/toto...')
#6 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#7 /Users/toto/.composer/vendor/webnet-fr/database-anonymize in /Users/toto/.composer/vendor/symfony/dependency-injection/Loader/FileLoader.php on line 32

```

**Comment by GautierArc** [comment]
Any news on this topic ?
